### ISSUE TITLE
Event Store 에 publish 되고 나면  evnet 목록을 clear 한다. 

### ISSUE THREAD

**Issue by yangwansu** [agistep/a-es.example#10]
https://github.com/agistep/a-es.example/blob/a65d6a0480d4416f885d948d8b231f55a6da4d57/event-core/src/main/java/io/agistep/event/EventList.java#L18

clear 는 현재 테스트에서 Tear Down 에서 만 사용한다. 

EventList 는 여러 Aggregate 에서 발생한 아직 다른 Aggregate instance 가 구체화 되기 전 Event 들을 목록으로 가지고 있다. 
EventList 의 Event 들이 이를 위해 EventStore 에 공개되는 시점 (publish ) 제거해주어야 한다. 

또한 가져오는 load 와 cleaer 가 대칭을 이루어야 한다.

**Comment by yangwansu** [comment]
https://github.com/agistep/a-es.example/blob/a65d6a0480d4416f885d948d8b231f55a6da4d57/event-core/src/main/java/io/agistep/event/ThreadLocalEventList.java#LL10C7-L10C27 

테스트가 부재하다.

**Comment by LenKIM** [comment]
이 부분 제가 진행할게요

**Comment by yangwansu** [comment]
@LenKIM Right!

**Comment by yangwansu** [comment]
추가적인 후속 이슈를 발굴 필요
