### ISSUE TITLE
구체적인 핸들러를 넣어야한다.

### ISSUE THREAD

**Issue by yangwansu** [agistep/a-es.example#16]
### Discussed in https://github.com/agistep/a-es.example/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **yangwansu** June 12, 2023</sup>
DomainApplier 에서 구체적인 핸들러를 기술해주어야한다. OCP 위반 
어떻게 하면 좋을까??

한가지 생각나는것은 
요고어떤가
 ```java 
@ EventHandler(name="???")
void on(Object payload) ...

```</div>

**Comment by LenKIM** [comment]
관련해서 Lombok 이 이용하는 Java Annotation Processor  기술 조사 중에 있습니다.
[관련 저장소](https://github.com/take-small-steps/understanding-java-annotation-processor)
