### ISSUE TITLE
Aggregate 별로 Event 의 순서가 있다.

### ISSUE THREAD

**Issue by yangwansu** [agistep/a-es.example#24]

**Comment by LenKIM** [comment]
close #27

지금 Event에 version 과 payload 가 deprecated가 됨. order  -> version 변경

Aggreagte 별로 Event 순서를 만드는 것도 종류가 있다.

EventBuilder.aggregate(aggregate) 에서 만들어지는 경우와 EventReorganizor.reorganize() 

**EventBuilder.aggregate(aggregate)**

setVersion(Object aggregate)

**EventReorganizor.reorganize(Object aggregate, Event anEvent)**

setVersion(Object aggregate, Event anEvent)
