### ISSUE TITLE
명시적으로 replay 를 aggregate 에 구현하도록 Practice 를 제공한다. 

### ISSUE THREAD

**Issue by yangwansu** [agistep/a-es.example#5]
#2 의 후속 

이벤트들에 의해서 재구성(replay) 되는 것을 표현 했다. 
또한 관련 생성자를 private 로 변경하여 암시적으로 해당 행위를 하지 못하도록 가이드한다. 

이후 고려하려하는 내용은 

Aggregate 에서 replay static method 에 대한 구현과 생성자의 private 접근자에 대한 선택은 온전하게 클라이언트에게 있다. 
고로 이부분을 매끄럽게 가이드 해 고민없이 해당 Practice 를 사용하도록 하는 장치가 필요할 것 같다.

**Comment by yangwansu** [comment]
lombok 처럼 ??? 
byte-buddy 를 사용해야하나?

```java

@EnableEventSourcing
public class SomeAggregate {



}


```

**Comment by yangwansu** [comment]
https://github.com/raphw/byte-buddy

**Comment by yangwansu** [comment]
byte-buddy 는 런타임에 동적 바이트 코드를 생성한다. 
이에 반해 annotation-processor 는 소스레벨에서 컴파일 전 소스코드를 생성한다.

**Comment by LenKIM** [comment]
관련해서 Lombok 에서 활용한 Java Annotation Processor 기술 조사 중에 있습니다.
[관련 저장소](https://github.com/take-small-steps/understanding-java-annotation-processor)

**Comment by LenKIM** [comment]
기존 클래스에 메소드를 추가하는 형태의 Annotation processor 개발은 약간의 Hack이 필요하다.

**Comment by yangwansu** [comment]
ed2a427d649d

**Comment by LenKIM** [comment]
Annotationprocessor 의 구현 후, Method 를 인식 못하는 문제로 해당 Issue Reopen
